---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Clear iptables rules
  ansible.builtin.command: iptables -F
  become: true

- name: Allow all traffic to port 80 using iptables
  ansible.builtin.command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
  become: true

- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - apache2
      - certbot
      - python3-certbot-apache
      - libapache2-mod-security2
    state: present

- name: Create log directory
  ansible.builtin.file:
    path: /var/log/apache_setup
    state: directory
    mode: '0755'

- name: Find all files in the sites-available directory
  ansible.builtin.find:
    paths: /etc/apache2/sites-available/
    recurse: true
    file_type: file
  register: found_files

- name: Delete all files in the sites-available directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ found_files.files }}"

- name: Log message
  ansible.builtin.shell: |
    echo "{{ item }}" >> /var/log/apache_setup/apache_setup.log
  loop:
    - "Checking for cloud instance boot completion"
    - "Cloud instance boot completed"
    - "Updating package index files"
    - "Setting up Apache"

- name: Disable default Apache site
  ansible.builtin.shell: |
    a2dissite 000-default.conf
  failed_when: false

- name: Enable necessary Apache modules
  ansible.builtin.shell: |
    a2enmod "{{ item }}"
  loop:
    - proxy
    - proxy_ajp
    - proxy_http
    - rewrite
    - deflate
    - headers
    - proxy_balancer
    - proxy_connect
    - proxy_html
    - security2
  failed_when: false

- name: Enable autoindex module to allow directory listings for letsencrypt challenge
  ansible.builtin.shell: |
    a2enmod autoindex
  failed_when: false

- name: Update Apache security config to turn off server signature
  ansible.builtin.replace:
    path: /etc/apache2/conf-available/security.conf
    regexp: 'ServerSignature On'
    replace: 'ServerSignature Off'

- name: Add fake server signature to Apache security config
  ansible.builtin.lineinfile:
    path: /etc/apache2/conf-available/security.conf
    line: "SecServerSignature {{ item.server_signature }}"
    create: true
  with_items: "{{ vhosts_dictionary }}"

- name: Update Apache security config to display full server tokens
  ansible.builtin.replace:
    path: /etc/apache2/conf-available/security.conf
    regexp: 'ServerTokens OS'
    replace: 'ServerTokens Full'

- name: Restart Apache to apply configuration changes
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    enabled: true

- name: Ensure the correct ownership of the webroot directory
  ansible.builtin.command: chown -Rv www-data:www-data /var/www/html/
  become: true

- name: Create webroot directory
  ansible.builtin.file:
    path: "/var/www/html/{{ item.redirector_domain }}"
    state: directory
    mode: '0755'
  with_items: "{{ vhosts_dictionary }}"
  failed_when: false

- name: Create HTTPS virtual host files
  ansible.builtin.template:
    src: pre_cert_apache_sslvhost.conf.j2
    dest: /etc/apache2/sites-available/rtssl_{{ item.redirector_domain }}.conf
    mode: '0644'
    force: true
  with_items: "{{ vhosts_dictionary }}"

- name: Create HTTP virtual host files
  ansible.builtin.template:
    src: pre_cert_apache_vhost.conf.j2
    dest: /etc/apache2/sites-available/rt_{{ item.redirector_domain }}.conf
    mode: '0644'
    force: true
  with_items: "{{ vhosts_dictionary }}"



- name: Add Apache modules for SSL, proxy, and headers
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - ssl
    - rewrite
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests
    - deflate
    - headers

- name: Disable unnecessary Apache module cache
  community.general.apache2_module:
    name: cache
    state: absent

- name: Enable Apache sites
  ansible.builtin.shell: |
    a2ensite rt_{{ item.redirector_domain }}
  with_items: "{{ vhosts_dictionary }}"

- name: Restart apache2
  ansible.builtin.systemd_service:
    name: apache2
    state: restarted
