# This output block defines an output that will display the unique ID of the CloudFront distribution
# Outputs are values that Terraform will display after creating the infrastructure
# They are useful for obtaining important information about the created resources
output "test_robertepimentel_com_cdn_1_CDN_ID" {
  # The value will be the ID of the CloudFront distribution we created
  # We use the reference to the aws_cloudfront_distribution resource followed by .id to obtain its identifier
  value = aws_cloudfront_distribution.test_robertepimentel_com_cdn_1.id
}

# This output block defines an output that will display the domain name of the CloudFront distribution
# This domain is what we will use to access the content distributed by CloudFront
output "test_robertepimentel_com_cdn_1_URL" {
  # The value will be the domain name assigned by CloudFront to this distribution
  # This domain will end in cloudfront.net and is automatically generated by AWS
  value = aws_cloudfront_distribution.test_robertepimentel_com_cdn_1.domain_name
}