---
# Este archivo contiene las tareas principales para instalar y configurar Mythic C2

# SECCIÓN 1: Instalación y Configuración de Docker Compose
# Instalación inicial de Docker Compose y configuración de sus componentes básicos
- name: Instalar Docker Compose standalone
  # Descarga la versión específica de Docker Compose desde GitHub y la instala en el sistema
  # Docker Compose es una herramienta que permite gestionar múltiples contenedores Docker
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'  # Establece permisos de ejecución para el archivo (rwxr-xr-x)

- name: Asegurar que docker-compose tenga permisos ejecutables
  # Asegura que Docker Compose tenga los permisos correctos para ejecutarse
  # Esta tarea es redundante por seguridad, en caso de que los permisos no se hayan establecido correctamente
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    mode: '0755'  # Permisos: propietario puede leer/escribir/ejecutar, otros pueden leer/ejecutar
    state: file

- name: Crear un enlace simbólico para docker-compose en /usr/bin
  # Crea un enlace simbólico para que docker-compose sea accesible desde cualquier ubicación del sistema
  ansible.builtin.file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
  become: true  # Ejecuta esta tarea con privilegios de superusuario

- name: Validar la instalación de docker-compose
  # Verifica que Docker Compose se haya instalado correctamente ejecutando el comando version
  ansible.builtin.command:
    cmd: docker-compose --version
  register: result  # Guarda el resultado del comando en una variable
  failed_when: result.rc != 0  # Falla si el comando no se ejecuta correctamente
  changed_when: false  # Indica que esta tarea no modifica el sistema

# SECCIÓN 2: Instalación de Paquetes Prerequisitos
- name: Validar paquetes expect y prerequisitos en un bucle
  # Instala y actualiza todos los paquetes necesarios para que Mythic funcione correctamente
  ansible.builtin.apt:
    pkg: "{{ item }}"  # Instala cada paquete de la lista
    state: present  # Asegura que se instale la última versión disponible
  loop:
    - gpg  # Herramienta para encriptación y firmas digitales
    - build-essential  # Paquetes necesarios para compilar software
    - mingw-w64  # Compilador para Windows
    - binutils-mingw-w64  # Herramientas binarias para compilación Windows
    - g++-mingw-w64  # Compilador C++ para Windows

# SECCIÓN 3: Gestión del Directorio de Instalación
- name: Verificar si el directorio de destino de Mythic existe
  # Verifica si el directorio donde se instalará Mythic ya existe
  ansible.builtin.stat:
    path: "{{ installation_path }}"  # Usa la variable definida en defaults/main.yml
  register: installation_path_stat  # Guarda el resultado para uso posterior

- name: Eliminar el directorio de destino de Mythic si existe y no es un directorio
  # Elimina el directorio si existe pero no es un directorio válido
  ansible.builtin.file:
    path: "{{ installation_path }}"
    state: absent
    force: true  # Fuerza la eliminación incluso si hay archivos
  when: installation_path_stat.stat.exists and not installation_path_stat.stat.isdir

- name: Asegurar que el directorio de destino de Mythic esté vacío si existe
  # Limpia el directorio de instalación si existe, eliminando todo su contenido
  ansible.builtin.shell: "rm -rf {{ installation_path }}/*"
  when: installation_path_stat.stat.exists and installation_path_stat.stat.isdir
  become: true  # Ejecuta esta tarea con privilegios de superusuario
  ignore_errors: true  # Ignora errores para asegurar que el directorio esté limpio

- name: Crear el directorio de destino de Mythic si no existe
  # Crea el directorio de instalación si no existe
  ansible.builtin.file:
    path: "{{ installation_path }}"
    state: directory
  when: not installation_path_stat.stat.exists
  become: true  # Ejecuta esta tarea con privilegios de superusuario

# SECCIÓN 4: Instalación y Configuración de Mythic
- name: Descargar Mythic
  # Descarga el código fuente de Mythic desde el repositorio Git especificado
  ansible.builtin.git:
    repo: "{{ mythic_repo }}"
    dest: "{{ installation_path }}"
    version: "{{ mythic_version }}"
  become: true  # Ejecuta esta tarea con privilegios de superusuario

- name: Verificar la configuración de mythic
  # Verifica si existe el archivo de configuración de Mythic
  ansible.builtin.stat:
    path: "{{ installation_path }}/.env"
  register: env_stat  # Guarda el resultado para uso posterior

- name: Compilar Mythic_CLI
  # Compila la herramienta de línea de comandos de Mythic
  ansible.builtin.command: make
  args:
    chdir: "{{ installation_path }}"  # Cambia al directorio de instalación antes de ejecutar el comando
  when: not env_stat.stat.exists  # Solo compila si el archivo de configuración no existe
  become: true  # Ejecuta esta tarea con privilegios de superusuario
  become_user: root  # Ejecuta esta tarea como el usuario root
  changed_when: false  # Indica que esta tarea no modifica el sistema

- name: Obtener información del contenedor de Mythic
  # Obtiene información sobre el contenedor Docker de Mythic
  community.docker.docker_container_info:
    name: mythic_server
  register: mythic_result  # Guarda el resultado para uso posterior
  become: true  # Ejecuta esta tarea con privilegios de superusuario

- name: Iniciar Mythic
  # Inicia el servidor Mythic usando la herramienta de línea de comandos
  ansible.builtin.command: "{{ installation_path }}/mythic-cli start"
  args:
    chdir: "{{ installation_path }}"  # Cambia al directorio de instalación antes de ejecutar el comando
  when: not mythic_result.exists  # Solo inicia si el contenedor no existe
  become_user: root  # Ejecuta esta tarea como el usuario root
  become: true  # Ejecuta esta tarea con privilegios de superusuario
  changed_when: false  # Indica que esta tarea no modifica el sistema

- name: Instalar Agentes
  # Incluye las tareas para instalar los agentes de Mythic definidos en la configuración
  ansible.builtin.include_tasks: install_agents.yml
  vars:
    agent: "{{ item }}"  # Pasa cada agente como variable a la tarea incluida
  loop: "{{ agents }}"  # Itera sobre la lista de agentes

# SECCIÓN 5: Limpieza y Finalización
- name: Detener Mythic usando ./mythic-cli
  # Detiene el servicio Mythic usando la herramienta CLI
  ansible.builtin.command: "./mythic-cli stop"
  args:
    chdir: "{{ installation_path }}"  # Cambia al directorio de instalación antes de ejecutar el comando
  become: true  # Ejecuta esta tarea con privilegios de superusuario
  changed_when: false  # Indica que esta tarea no modifica el sistema

- name: Detener docker-compose de Mythic
  # Detiene todos los contenedores de Mythic y limpia los recursos huérfanos
  # Esto asegura que no queden contenedores o recursos sin usar en el sistema
  ansible.builtin.command: "docker-compose down --remove-orphans"
  args:
    chdir: "{{ installation_path }}"  # Cambia al directorio de instalación antes de ejecutar el comando
  become: true  # Ejecuta esta tarea con privilegios de superusuario
  changed_when: false  # Indica que esta tarea no modifica el sistema
